# ============================================================
# 🎨 DRAW / CANVAS MODULE (PYROGRAM VERSION)
# ============================================================

__mod_name__ = "🎨 ᴅʀᴀᴡ"

__help__ = """
*🎨 ᴅʀᴀᴡ ᴍᴏᴅᴜʟᴇ* — Draw text or generate visual text art directly via image canvas (Utility).

• `/draw [text]` — Render custom text onto a styled image canvas and send it as a photo.
"""

import io
import logging
from PIL import Image, ImageDraw, ImageFont
from pyrogram import filters
from pyrogram.types import Message

logger = logging.getLogger("DRAW")

def register_draw_system(app):

    @app.on_message(filters.command("draw"))
    async def draw_cmd(client, message: Message):
        if len(message.command) < 2:
            return await message.reply("⚠️ **Please provide text to draw! Example:** `drawing hello nomads`")

        text_to_draw = " ".join(message.command[1:])

        status_msg = await message.reply("🎨 **Generating canvas image...**")

        try:
            # Create a blank image canvas (RGB, dark/stylish background theme)
            width, height = 800, 400
            bg_color = (20, 20, 30)
            image = Image.new("RGB", (width, height), color=bg_color)
            draw = ImageDraw.Draw(image)

            # Attempt to load a default TrueType font or fallback
            try:
                # Standard Linux system font path fallback
                font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 36)
            except IOError:
                try:
                    font = ImageFont.load_default()
                except Exception:
                    font = None

            # Add decorative header / borders
            draw.rectangle([(20, 20), (width - 20, height - 20)], outline=(70, 130, 180), width=3)
            
            # Text positioning and multi-line wrapping logic
            # Simple text rendering inside the box
            text_x, text_y = 50, 100
            
            if font:
                draw.text((text_x, text_y), text_to_draw, fill=(255, 255, 255), font=font)
                draw.text((50, height - 60), "— Generated by Nomad Bot ⚡", fill=(150, 150, 150), font=ImageFont.load_default() if hasattr(ImageFont, "load_default") else None)
            else:
                draw.text((text_x, text_y), text_to_draw, fill=(255, 255, 255))

            # Save to an in-memory byte buffer
            output_buffer = io.BytesIO()
            output_buffer.name = "nomad_canvas.png"
            image.save(output_buffer, format="PNG")
            output_buffer.seek(0)

            # Send photo
            await message.reply_photo(
                photo=output_buffer,
                caption=f"🎨 **Canvas Rendered for:** `{message.from_user.first_name}`"
            )
            await status_msg.delete()

        except Exception as e:
            logger.error(f"[Draw Error]: {e}")
            await status_msg.edit_text(f"❌ **Failed to generate canvas image:** `{str(e)}`")
